name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTENT_COMPARISON: true
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"
     
      - name: Action-Automerge
        uses: mtanzi/action-automerge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ steps.pull.outputs.pull_request_number }}
          merge_method: "squash"
          commit_message: "Merge master into develop"
          source: "master"
          target: "develop"
          
#       - name : merge conflicts in PR
#         if: failure()
#         id: slack
#         uses: slackapi/slack-github-action@v1.23.0
#         with:
#           channel-id: 'CG0L8G78C'
#           slack-message: "GitHub merge conflict test \n job:${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#         env:
#           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

        
        
        
