name: Sync
on:
  push:
    branches:
      - master

jobs:
  #   migrations_linter_job:
  #         runs-on: ubuntu-latest
  #         name: Alert for checking breaking migrations
  #         steps:
  #             - uses: actions/checkout@v3
  #               with:
  #                   fetch-depth: 0

  #             - name: Get changed files
  #               id: changed-files
  #               uses: tj-actions/changed-files@v31.0.0

  #             - name: setup python
  #               uses: actions/setup-python@v4.2.0
  #               with:
  #                   python-version: 3.10.8

  #             - name: Run migrations linter
  #               run: |
  #                   python migrations_linter.py ${{ steps.changed-files.outputs.all_changed_files }}

  sync-branches:
    #needs: migrations_linter_job
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: setup python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.8

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop

      - name: git logs
        run: |
          log="$(git log --pretty=short -n 10)"
          echo 'LOGS=$log' >> $GITHUB_ENV
      
      - name: get logs
      
        run: |
          import os
          import json
          resp=os.environ['LOGS']
          print(resp)

        shell: python {0}
        
          
          
      - name: Get Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
          

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTENT_COMPARISON: true
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"

      - name: get develop branch commits
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          resp="$(gh api /repos/HemendraSharma04/fastapi_blog/branches/develop)"
          echo 'RESP='$resp >> $GITHUB_ENV

     
          

      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          import os
          import json
          resp=os.environ['RESP']
          json_object = json.loads(resp)
          print(type(json_object))
          print(json_object)

        shell: python {0}

      - name: test py shell
        id: pshell
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

          USER: ${{github.event.commits[0].author.username}}
        run: |
          import os
          import json
          usr=os.environ['USER']
          with open('users.json', 'r') as openfile:
            users = json.load(openfile)
          print(users[usr])
          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "w") as myfile:
            temp="SLACK_USER"+"="+users[usr]
            myfile.write(temp)
        shell: python {0}

      - name: get env variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo ${{env.SLACK_USER}}
          ls
          pwd

      - name: Action-Automerge
        if: Success()
        id: "automerge"
        uses: mtanzi/action-automerge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ steps.pull.outputs.pull_request_number }}
          merge_method: "squash"
          commit_message: "Merge master into develop"
          source: "master"
          target: "develop"
#       - name: merge conflicts in PR
#         if: failure()
#         id: slack
#         env:
#           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#           USER: ${{ format('steps.username.outputs.{0}',steps.string.outputs.uppercase) }}

#         uses: slackapi/slack-github-action@v1.23.0
#         with:
#           channel-id: "CG64UFLLW"
#           slack-message: "GitHub merge conflict test \n job:${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n user : <@${{env.SLACK_USER}}>\n"
