name: Sync
on:
  push:
    branches:
      - master

jobs:
  # migrations_linter_job:
  #       runs-on: ubuntu-latest
  #       name: Alert for checking breaking migrations
  #       steps:
  #           - uses: actions/checkout@v3
  #             with:
  #                 fetch-depth: 0

  #           - name: Get changed files
  #             id: changed-files
  #             uses: tj-actions/changed-files@v31.0.0

  #           - name: setup python
  #             uses: actions/setup-python@v4.2.0
  #             with:
  #                 python-version: 3.10.8

  #           - name: Run migrations linter
  #             run: |
  #                 python migrations_linter.py ${{ steps.changed-files.outputs.all_changed_files }}

  sync-branches:
    # needs: migrations_linter_job
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTENT_COMPARISON: true
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"

      - name: test user
        env:
          USER: ${{ toJSON(github.event.commits[0].author.username ) }}
        run: echo "$USER"

      - name: test secret
        env:
          SLACK_USER: ${{ format('vars.SLACK_{0}',github.event.commits[0].author.username ) }}

        run: echo "@$SLACK_USER"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Action-Automerge
        if: Success()
        id: "automerge"
        uses: mtanzi/action-automerge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ steps.pull.outputs.pull_request_number }}
          merge_method: "squash"
          commit_message: "Merge master into develop"
          source: "master"
          target: "develop"

      - name: merge conflicts in PR
        if: failure()
        id: slack
        env:
          USER: ${{ toJSON(github.event.commits[0].author.username ) }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER: ${{ format('vars.SLACK_{0}',github.event.commits[0].author.username ) }}

        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "CG64UFLLW"
          slack-message: "GitHub merge conflict test \n job:${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n user : @${{SLACK_USER}} }"
